version: '3'
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: fake_db_password
            POSTGRES_USER: fake_db_user
            POSTGRES_DB: luckycall

    run_migrations:
        build: .
        command: ../scripts/run_migrations.sh
        environment:
            DJANGO_SETTINGS_MODULE: lucky_call.settings.prod
        depends_on:
            - db
        links:
            - db

    app01:
        build: .
        command: gunicorn lucky_call.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
        restart: always
        environment:
            DJANGO_SETTINGS_MODULE: lucky_call.settings.prod
        depends_on:
            - db
        links:
            - db

    app02:
        build: .
        command: gunicorn lucky_call.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
        restart: always
        environment:
            DJANGO_SETTINGS_MODULE: lucky_call.settings.prod
        depends_on:
            - db
        links:
            - db

    web:
        image: nginx
        restart: always
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        depends_on:
            - app01
            - app02
        links:
            - app01
            - app02
