# Generated by Django 2.2.4 on 2019-08-10 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
    ]
