# Generated by Django 2.2.4 on 2019-08-11 10:42

from django.db import migrations, models
import django.db.models.deletion
import guess.models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyCallContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('result', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='contest',
            field=models.ForeignKey(blank=True, default=guess.models.LuckyCallContest.get_active_contest, null=True, on_delete=django.db.models.deletion.CASCADE, to='guess.LuckyCallContest'),
        ),
    ]
