# Generated by Django 2.2.4 on 2019-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_auto_20190811_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
