# Generated by Django 2.2.4 on 2019-08-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0003_guess_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckycallcontest',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guess.Guess'),
        ),
    ]
