# Generated by Django 2.2.4 on 2019-08-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0004_luckycallcontest_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
